-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS T
    UNION ALL
    SELECT T + 1 FROM TIME
    WHERE T < 23
)


SELECT TIME.T AS "HOUR", COUNT(HOUR(ANIMAL_OUTS.DATETIME)) AS "COUNT"
FROM TIME LEFT JOIN ANIMAL_OUTS
    ON TIME.T = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY TIME.T;