from django.shortcuts import render
import random

# Create your views here.
def is_odd_even(request, number):
    context = {
        "num": number,
    }

    return render(request, "is-odd-even.html", context)


def calculate(request, a, b):
    context = {
        "num1": a,
        "num2": b,
    }

    return render(request, "calculate.html", context)


def pastlife_input(request):
    return render(request, "pastlife-input.html")


def pastlife_output(request):
    adjective = [
        "가냘픈",
        "가는",
        "가엾은",
        "거센",
        "거친",
        "검은",
        "게으른",
        "고달픈",
        "고른",
        "고마운",
        "고운",
        "고픈",
        "곧은",
        "괜찮은",
        "구석진",
        "굳은",
        "굵은",
        "귀여운",
        "그런",
        "그른",
        "그리운",
        "기다란",
        "기쁜",
        "긴",
        "깊은",
        "깨끗한",
        "나쁜",
        "날랜",
        "날카로운",
        "너그러운",
        "너른",
        "널따란",
        "넓은",
        "네모난",
        "노란",
        "누런",
        "느린",
        "더러운",
        "덜된",
        "동그란",
        "돼먹잖은",
        "둥그런",
        "둥근",
        "드문",
        "딱한",
        "뛰어난",
        "뜨거운",
        "멋진",
        "메마른",
        "모난",
        "못난",
        "못된",
        "못생긴",
        "무거운",
        "무딘",
        "무서운",
        "미끄러운",
        "미운",
        "바람직한",
        "반가운",
        "밝은",
        "보드라운",
        "부드러운",
        "붉은",
        "비싼",
        "빠른",
        "빨간",
        "뻘건",
        "뼈저린",
        "뽀얀",
        "뿌연",
        "새로운",
        "서툰",
        "섣부른",
        "성가신",
        "센",
        "수줍은",
        "쉬운",
        "스스러운",
        "슬픈",
        "시원찮은",
        "쌀쌀맞은",
        "쏜살같은",
        "아니꼬운",
        "아름다운",
        "아쉬운",
        "아픈",
        "안된",
        "안쓰러운",
        "안타까운",
        "알맞은",
        "약빠른",
        "약은",
        "어두운",
        "어린",
        "언짢은",
        "엄청난",
        "예쁜",
        "올바른",
        "외로운",
        "우스운",
        "의심스런",
        "작은",
        "잘난",
        "잘빠진",
        "잘생긴",
        "재미있는",
        "젊은",
        "점잖은",
        "조그만",
        "주제넘은",
        "즐거운",
        "지혜로운",
        "짓궂은",
        "짧은",
        "케케묵은",
        "큰",
        "탐스러운",
        "턱없는",
        "푸른",
        "한결같은",
        "희망찬",
        "흰",
    ]

    noun = [
        "고양이",
        "강아지",
        "거북이",
        "토끼",
        "뱀",
        "사자",
        "호랑이",
        "표범",
        "치타",
        "하이에나",
        "기린",
        "코끼리",
        "코뿔소",
        "하마",
        "악어",
        "펭귄",
        "부엉이",
        "올빼미",
        "곰",
        "돼지",
        "소",
        "닭",
        "독수리",
        "타조",
        "고릴라",
        "오랑우탄",
        "침팬지",
        "원숭이",
        "코알라",
        "캥거루",
        "고래",
        "상어",
        "칠면조",
        "직박구리",
        "쥐",
        "청설모",
        "메추라기",
        "앵무새",
        "삵",
        "스라소니",
        "판다",
        "오소리",
        "오리",
        "거위",
        "백조",
        "두루미",
        "고슴도치",
        "두더지",
        "우파루파",
        "맹꽁이",
        "너구리",
        "개구리",
        "두꺼비",
        "카멜레온",
        "이구아나",
        "노루",
        "제비",
        "까치",
        "고라니",
        "수달",
        "당나귀",
        "순록",
        "염소",
        "공작",
        "바다표범",
        "들소",
        "박쥐",
        "참새",
        "물개",
        "바다사자",
        "살모사",
        "구렁이",
        "얼룩말",
        "산양",
        "멧돼지",
        "카피바라",
        "도롱뇽",
        "북극곰",
        "퓨마",
        "미어캣",
        "코요테",
        "라마",
        "딱따구리",
        "기러기",
        "비둘기",
        "스컹크",
        "돌고래",
        "까마귀",
        "매",
        "낙타",
        "여우",
        "사슴",
        "늑대",
        "재규어",
        "알파카",
        "양",
        "다람쥐",
        "담비",
    ]

    context = {
        "name": request.GET.get("name"),
        "adjective": random.choice(adjective),
        "noun": random.choice(noun),
    }

    return render(request, "pastlife-output.html", context)


def k_lipsum_input(request):
    return render(request, "k-lipsum-input.html")


def k_lipsum_output(request):
    p = request.GET.get("p_cnt")
    w = request.GET.get("w_cnt")

    word = ["감", "나무", "다람쥐", "라이온킹", "마에스트로"]
    p_list = []

    for i in range(int(p)):
        temp = [random.choice(word) for j in range(int(w))]
        p_list.append(temp)

    context = {
        "p_list": p_list,
    }
    return render(request, "k-lipsum-output.html", context)
